update=Tue 27 May 2014 22:20:01 EST
last_client=pcbnew
[cvpcb]
version=1
NetIExt=net
[cvpcb/libraries]
EquName1=devcms
[pcbnew]
version=1
LastNetListRead=ra8875-2layer.net
UseCmpFile=1
PadDrill="    0.600000"
PadDrillOvalY="    0.600000"
PadSizeH="    1.500000"
PadSizeV="    1.500000"
PcbTextSizeV="    1.500000"
PcbTextSizeH="    1.500000"
PcbTextThickness="    0.300000"
ModuleTextSizeV="    1.000000"
ModuleTextSizeH="    1.000000"
ModuleTextSizeThickness="    0.150000"
SolderMaskClearance="    0.000000"
SolderMaskMinWidth="    0.000000"
DrawSegmentWidth="    0.200000"
BoardOutlineThickness="    0.100000"
ModuleOutlineThickness="    0.150000"
[pcbnew/libraries]
LibDir=
LibName1=sockets
LibName2=connect
LibName3=discret
LibName4=pin_array
LibName5=divers
LibName6=smd_capacitors
LibName7=smd_resistors
LibName8=smd_crystal&oscillator
LibName9=smd_dil
LibName10=smd_transistors
LibName11=libcms
LibName12=display
LibName13=led
LibName14=dip_sockets
LibName15=pga_sockets
LibName16=valves
LibName17=/media/AOSPDrive/anelok/kicad-libs/modules/inductor-2p
LibName18=/media/AOSPDrive/anelok/kicad-libs/modules/lp2032sm
LibName19=/media/AOSPDrive/anelok/kicad-libs/modules/stdpass
LibName20=/media/AOSPDrive/anelok/kicad-libs/modules/zx62m-b-5p
LibName21=/media/AOSPDrive/anelok/kicad-libs/modules/zx62-b-5pa
LibName22=/media/AOSPDrive/anelok/kicad-libs/modules/xtal-4
LibName23=/media/AOSPDrive/anelok/kicad-libs/modules/xtal-2
LibName24=/media/AOSPDrive/anelok/kicad-libs/modules/xlr-socket
LibName25=/media/AOSPDrive/anelok/kicad-libs/modules/xlr-plug
LibName26=/media/AOSPDrive/anelok/kicad-libs/modules/usb_a_rcpt_smt
LibName27=/media/AOSPDrive/anelok/kicad-libs/modules/usb_a_plug_smt
LibName28=/media/AOSPDrive/anelok/kicad-libs/modules/usb-a-pcb
LibName29=/media/AOSPDrive/anelok/kicad-libs/modules/usb-a-dual-recept-r
LibName30=/media/AOSPDrive/anelok/kicad-libs/modules/tswa
LibName31=/media/AOSPDrive/anelok/kicad-libs/modules/tssop5
LibName32=/media/AOSPDrive/anelok/kicad-libs/modules/tsop
LibName33=/media/AOSPDrive/anelok/kicad-libs/modules/to
LibName34=/media/AOSPDrive/anelok/kicad-libs/modules/tactile-sw-spst-ra-dip
LibName35=/media/AOSPDrive/anelok/kicad-libs/modules/sw-spdt-smt
LibName36=/media/AOSPDrive/anelok/kicad-libs/modules/ssop
LibName37=/media/AOSPDrive/anelok/kicad-libs/modules/spacer
LibName38=/media/AOSPDrive/anelok/kicad-libs/modules/sot23
LibName39=/media/AOSPDrive/anelok/kicad-libs/modules/sot
LibName40=/media/AOSPDrive/anelok/kicad-libs/modules/sot-323
LibName41=/media/AOSPDrive/anelok/kicad-libs/modules/soic
LibName42=/media/AOSPDrive/anelok/kicad-libs/modules/rj45
LibName43=/media/AOSPDrive/anelok/kicad-libs/modules/rca-3-ra
LibName44=/media/AOSPDrive/anelok/kicad-libs/modules/qfp
LibName45=/media/AOSPDrive/anelok/kicad-libs/modules/qfn
LibName46=/media/AOSPDrive/anelok/kicad-libs/modules/phonejack
LibName47=/media/AOSPDrive/anelok/kicad-libs/modules/pads
LibName48=/media/AOSPDrive/anelok/kicad-libs/modules/pads-array
LibName49=/media/AOSPDrive/anelok/kicad-libs/modules/mini-usb
LibName50=/media/AOSPDrive/anelok/kicad-libs/modules/mic-ra-dip
LibName51=/media/AOSPDrive/anelok/kicad-libs/modules/memcard8-amp-10100660
LibName52=/media/AOSPDrive/anelok/kicad-libs/modules/meander-2450MHz
LibName53=/media/AOSPDrive/anelok/kicad-libs/modules/mdip
LibName54=/media/AOSPDrive/anelok/kicad-libs/modules/lga
LibName55=/media/AOSPDrive/anelok/kicad-libs/modules/ledsmd
LibName56=/media/AOSPDrive/anelok/kicad-libs/modules/ir
LibName57=/media/AOSPDrive/anelok/kicad-libs/modules/header
LibName58=/media/AOSPDrive/anelok/kicad-libs/modules/he-shrouded
LibName59=/media/AOSPDrive/anelok/kicad-libs/modules/he-2row-dip
LibName60=/media/AOSPDrive/anelok/kicad-libs/modules/fiducial
LibName61=/media/AOSPDrive/anelok/kicad-libs/modules/evqq7
LibName62=/media/AOSPDrive/anelok/kicad-libs/modules/eus
LibName63=/media/AOSPDrive/anelok/kicad-libs/modules/er-oled-fpc30
LibName64=/media/AOSPDrive/anelok/kicad-libs/modules/e-switch320
LibName65=/media/AOSPDrive/anelok/kicad-libs/modules/dvi-recept-ra
LibName66=/media/AOSPDrive/anelok/kicad-libs/modules/do-214
LibName67=/media/AOSPDrive/anelok/kicad-libs/modules/dip4of6
LibName68=/media/AOSPDrive/anelok/kicad-libs/modules/dip
LibName69=/media/AOSPDrive/anelok/kicad-libs/modules/din-5
LibName70=/media/AOSPDrive/anelok/kicad-libs/modules/dfn
LibName71=/media/AOSPDrive/anelok/kicad-libs/modules/dcjack
LibName72=/media/AOSPDrive/anelok/kicad-libs/modules/c-t-smd
LibName73=/media/AOSPDrive/anelok/kicad-libs/modules/c-smd
LibName74=/media/AOSPDrive/anelok/kicad-libs/modules/bga
LibName75=/media/AOSPDrive/anelok/kicad-libs/modules/bat-clip-aa-th
LibName76=/media/AOSPDrive/anelok/kicad-libs/modules/8_10-socket-ra
LibName77=/media/AOSPDrive/anelok/kicad-libs/modules/8_10-socket-ra-push-pull
LibName78=/media/AOSPDrive/anelok/kicad-libs/modules/8_10-card
